
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'ECD88615902865D89A5FBA42406F93CF'
    
_lr_action_items = {'ALL':([2,23,],[10,-6,]),'AMPM':([21,],[23,]),'.':([13,],[16,]),'LINUX':([0,],[4,]),'INTEGER':([0,2,9,12,14,16,17,18,19,20,22,23,24,25,26,27,],[5,9,13,15,13,19,13,21,-10,13,13,-6,13,13,13,13,]),':':([5,15,],[12,18,]),'CPU':([2,23,],[11,-6,]),'$end':([0,1,3,4,6,7,8,10,11,19,28,],[-11,-3,0,-1,-5,-2,-4,-8,-7,-10,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'all':([0,],[1,]),'float':([9,14,17,20,22,24,25,26,27,],[14,17,20,22,24,25,26,27,28,]),'start':([0,],[3,]),'time':([0,],[2,]),'data':([0,],[6,]),'cpu':([0,],[7,]),'empty':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> LINUX','start',1,'p_start','PLYmpstat.py',49),
  ('start -> cpu','start',1,'p_start','PLYmpstat.py',50),
  ('start -> all','start',1,'p_start','PLYmpstat.py',51),
  ('start -> empty','start',1,'p_start','PLYmpstat.py',52),
  ('start -> data','start',1,'p_start','PLYmpstat.py',53),
  ('time -> INTEGER : INTEGER : INTEGER AMPM','time',6,'p_time','PLYmpstat.py',58),
  ('cpu -> time CPU','cpu',2,'p_cpu','PLYmpstat.py',62),
  ('all -> time ALL','all',2,'p_all','PLYmpstat.py',66),
  ('data -> time INTEGER float float float float float float float float float','data',11,'p_data','PLYmpstat.py',70),
  ('float -> INTEGER . INTEGER','float',3,'p_float','PLYmpstat.py',74),
  ('empty -> <empty>','empty',0,'p_empty','PLYmpstat.py',78),
]
